ajaxdemo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ajaxit.urls')),
]

ajaxit/urls.py
from django.conf.urls import url
from django.contrib import admin
from ajaxit import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajaxit/addemployee/$', views.addemployee, name='addemployee'),
    url(r'^ajaxit/delemployee/$', views.delemployee, name='delemployee'),
    url(r'^ajaxit/editemployee/$', views.editemployee, name='editemployee'),
    url(r'^ajaxit/editemployeefull/$', views.editemployeefull, name='editemployeefull'),

]

ajaxit/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Employees(models.Model):
    emp_name = models.CharField(max_length=100)
    emp_email = models.CharField(max_length=100)
    emp_dob = models.DateField()
    emp_pass = models.CharField(max_length=100)

ajaxit/forms.py
from django import forms
from ajaxit.models import Employees

# from ajaxdemo import settings
DATE_INPUT_FORMATS = ['%d-%m-%Y']
# formats=DATE_INPUT_FORMATS
class EmployeeForm(forms.ModelForm):
    emp_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control play', 'placeholder': 'Employee Name','required':'true'}),
        label='')

    emp_email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control play', 'placeholder': 'Email Address','required':'true'}),
        label='')
    emp_dob = forms.DateField(
        widget=forms.DateInput(format="%d-%m-%Y",attrs={'class': 'form-control play', 'placeholder': 'Date of Birth(yyyy-mm-dd)','required':'true'}),
        label='')
    emp_pass = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control play', 'placeholder': 'Password','required':'true'}),
        label='')

    class Meta:
        model = Employees
        fields = ['emp_name', 'emp_email', 'emp_dob', 'emp_pass']

ajaxit/views.py
from django.shortcuts import render
from ajaxit.forms import EmployeeForm
# Create your views here.
from ajaxit.models import Employees
from django.shortcuts import HttpResponse
import json
import time,datetime
def index(request):
    emp_list=Employees.objects.all()

    if request.method == 'POST':
        if 'emp_name' in request.POST and 'emp_email' in request.POST and 'emp_dob' in request.POST and 'emp_pass' in request.POST:
            form = EmployeeForm(request.POST)
            if form.is_valid():
                form.save()
                form = EmployeeForm()
                if not emp_list:
                    return render(request, 'ajaxit/index.html', {'form': form, 'msg': 'Employee Added'})
                else:
                    return render(request, 'ajaxit/index.html', {'form': form,'empx':emp_list, 'msg': 'Employee Added'})

            if not emp_list:
                return render(request, 'ajaxit/index.html',
                          {'form': form, 'msg': 'Invalid Data'})
            else:
                return render(request, 'ajaxit/index.html',
                              {'form': form,'empx':emp_list,'msg': 'Invalid Data'})
        form = EmployeeForm()
        if not emp_list:
            return render(request, 'ajaxit/index.html',{'form':form})
        else:
            return render(request, 'ajaxit/index.html',{'form':form,'empx':emp_list})

    form = EmployeeForm()
    if not emp_list:
        return render(request, 'ajaxit/index.html', {'form': form})
    else:
        return render(request, 'ajaxit/index.html', {'form': form,'empx':emp_list})


def addemployee(request):

    employee_name = request.POST.get('employee_name', 'root')
    employee_email= request.POST.get('employee_email', 'root@mail.com')
    employee_dob = request.POST.get('employee_dob', '08-01-1993')
    employee_pass = request.POST.get('employee_pass', 'toor')

    emp_obj = Employees(emp_name=str(employee_name),emp_email=str(employee_email),emp_dob=str(employee_dob),emp_pass=str(employee_pass))
    emp_obj.save()
    myemps=Employees.objects.all()
    strx=''
    strx+='<h3 class="text-success text-center page-header">List of Employees</h3>'

    strx+='<table class="table table-striped table-hover table-bordered table-condensed">'

    strx+="<tr><th class='info'>S.N.</th><th class='info'>Name</th><th class='info'>Email</th><th class='info'>D.O.B.</th><th class='info' colspan='2'>Actions</th></tr>"

    for i in range(len(myemps)):
        strx+='<tr>'
        strx+='<td>'+str(i+1)+'</td>'
        strx+='<td>'+myemps[i].emp_name+'</td>'
        strx+='<td>'+myemps[i].emp_email+'</td>'
        strx+='<td>'+str(myemps[i].emp_dob)+'</td>'
        strx+='<td>'+'<button onclick=del("'+str(myemps[i].id)+'")>Delete</button>'
        strx+='<td>'+'<button onclick=edit("'+str(myemps[i].id)+'")>Edit</button>'

        strx+='</tr>'
    strx+='</table>'
    # print(strx)

    return HttpResponse(strx)

def delemployee(request):

    employee_id = request.POST.get('employee_id', '-1')
    Employees.objects.filter(id=employee_id).delete()
    strx=''
    strx+='<h3 class="text-success text-center page-header">List of Employees</h3>'

    strx+='<table class="table table-striped table-hover table-bordered table-condensed">'
    strx+="<tr><th class='info'>S.N.</th><th class='info'>Name</th><th class='info'>Email</th><th class='info'>D.O.B.</th><th class='info' colspan='2'>Actions</th></tr>"
    myemps=Employees.objects.all()
    for i in range(len(myemps)):
        strx+='<tr>'
        strx+='<td>'+str(i+1)+'</td>'

        strx+='<td>'+myemps[i].emp_name+'</td>'
        strx+='<td>'+myemps[i].emp_email+'</td>'
        strx+='<td>'+str(myemps[i].emp_dob)+'</td>'
        strx+='<td>'+'<button onclick=del("'+str(myemps[i].id)+'")>Delete</button>'
        strx+='<td>'+'<button onclick=edit("'+str(myemps[i].id)+'")>Edit</button>'

        strx+='</tr>'
    strx+='</table>'
    return HttpResponse(strx)

def editemployee(request):

    employee_id = request.POST.get('employee_id', '-1')
    # empk=Employees.objects.filter(id=employee_id)
    myemps=Employees.objects.filter(id=employee_id)
    empdict={}
    for i in myemps:
        empdict['emp_id']=i.id
        empdict['emp_name']=i.emp_name
        empdict['emp_email']=i.emp_email
        empdict['emp_dob']=str(i.emp_dob)
        empdict['emp_pass']=str(i.emp_pass)

    return HttpResponse(json.dumps(empdict))


def editemployeefull(request):
    employee_name = request.POST.get('employee_name', 'root')
    employee_email = request.POST.get('employee_email', 'root@mail.com')
    employee_dob = request.POST.get('employee_dob', '08-01-1993')
    employee_pass = request.POST.get('employee_pass', 'toor')
    employee_id=request.POST.get('employee_id', 'root')
    myemps=Employees.objects.filter(id=employee_id)
    myemps.update(emp_name=employee_name,emp_email=employee_email,emp_dob=employee_dob,emp_pass=employee_pass)
    myemps = Employees.objects.all()
    strx=''
    strx+='<h3 class="text-success text-center page-header">List of Employees</h3>'
    strx += '<table class="table table-striped table-hover table-bordered table-condensed">'
    strx += "<tr><th class='info'>S.N.</th><th class='info'>Name</th><th class='info'>Email</th><th class='info'>D.O.B.</th><th class='info' colspan='2'>Actions</th></tr>"

    for i in range(len(myemps)):
        strx += '<tr>'
        strx += '<td>' + str(i + 1) + '</td>'

        strx += '<td>' + myemps[i].emp_name + '</td>'
        strx += '<td>' + myemps[i].emp_email + '</td>'
        strx += '<td>' + str(myemps[i].emp_dob) + '</td>'
        strx += '<td>' + '<button onclick=del("' + str(myemps[i].id) + '")>Delete</button>'
        strx += '<td>' + '<button onclick=edit("' + str(myemps[i].id) + '")>Edit</button>'

        strx += '</tr>'
    strx += '</table>'
    return HttpResponse(strx)

ajaxit/templates/ajaxit/index.html
<!DOCTYPE html>

{% load bootstrap3 %}
{%load staticfiles%}

<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title> Ajax Demo</title>
        <link href="{%static 'css/iao-alert.css'%}" rel="stylesheet"/>
        <script src="{%static 'js/jquery.min.js'%}"></script>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
        <link href="{%static 'css/styles.css'%}" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Chango" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <script src="{%static 'js/javas.js'%}"></script>
    <script src="{%static 'js/iao-alert.jquery.js'%}"></script>
    <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link href="{%static 'css/dcalendar.picker.css'%}" rel="stylesheet"/>
    <script src="{%static 'js/dcalendar.picker.js'%}"></script>

    <script>
$(function(){
    $('#id_emp_dob').dcalendarpicker({
      format: 'yyyy-mm-dd'}

    );
    });
</script>
 </head>
<body>

{%if form%}
<div class="col-sm-3"></div>
<div class="col-sm-6">

<h2 class="text-center page-header text-danger">Welcome to Ajax Tutorial</h2>
{{form.as_p}}
<button id="emp_add" class="btn btn-danger btn-md">Add Employee</button>

    {%if empx%}
    <div class="bg-danger" id="emplist">
    <h3 class="text-success text-center page-header">List of Employees</h3>
        <table class="table table-striped table-hover table-bordered table-condensed">
        <tr><th class='info'>S.N.</th><th class='info'>Name</th><th class='info'>Email</th><th class='info'>D.O.B.</th><th class='info' colspan='2'>Actions</th></tr>
        {%for employee in empx%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{employee.emp_name}}</td>
                <td>{{employee.emp_email}}</td>
                <td>{{employee.emp_dob}}</td>
                <td class='success'><button onClick='del({{employee.id}})'>Delete</button></td>
                <td class='success'><button name='editbtn' onClick='edit({{employee.id}})'>Edit</button></td>
            </tr>

        {%endfor%}
            </table>

    </div>


    {%else%}
    <div class="bg-danger" id="emplist"></div>
    {%endif%}


</div>
<div class="col-sm-3"></div>

{%endif%}
</body>
</html>